{foxy} Add clang to ROS_WORLD_SKIP_GROUPS
* fixes:
ERROR: Nothing RPROVIDES 'UNRESOLVED-clang-format' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-clang-format_0.9.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-format' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-format']
NOTE: Runtime target 'ament-clang-format' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-format', 'UNRESOLVED-clang-format']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy', 'ament-clang-format', 'UNRESOLVED-clang-format']
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'ament-clang-format', 'UNRESOLVED-clang-format']
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-foxy', 'ament-clang-format', 'UNRESOLVED-clang-format']
ERROR: Nothing RPROVIDES 'ament-clang-format-dev' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-clang-format_0.9.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ament-clang-format-dev'
NOTE: Runtime target 'ament-clang-format-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-format-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-clang-tidy' (but ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-clang-tidy_0.9.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-tidy']
NOTE: Runtime target 'ament-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-tidy', 'UNRESOLVED-clang-tidy']
NOTE: Runtime target 'ament-clang-tidy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-clang-tidy-dev', 'UNRESOLVED-clang-tidy']
ERROR: Nothing RPROVIDES 'UNRESOLVED-clang-format-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-clang-format_0.9.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-format-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-format-native']
NOTE: Runtime target 'ament-cmake-clang-format' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-format', 'ament-clang-format-native', 'UNRESOLVED-clang-format-native']
NOTE: Runtime target 'ament-cmake-clang-format-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-format-dev', 'ament-clang-format-native', 'UNRESOLVED-clang-format-native']
ERROR: Nothing RPROVIDES 'UNRESOLVED-clang-tidy-native' (but virtual:native:ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ament-lint/ament-clang-tidy_0.9.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-clang-tidy-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-clang-tidy-native']
NOTE: Runtime target 'ament-cmake-clang-tidy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-tidy', 'ament-clang-tidy-native', 'UNRESOLVED-clang-tidy-native']
NOTE: Runtime target 'ament-cmake-clang-tidy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-clang-tidy-dev', 'ament-clang-tidy-native', 'UNRESOLVED-clang-tidy-native']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>