{melodic} rosping: remove strange sudo calls from CMakeLists.txt
* the install target sets SETUID permission, so it should be added automatically without
  another chown/chmod
* resolves following issues shown in log.do_install:
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/package.xml
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/lib/rosping/rosping
  ERROR: ld.so: object 'libpseudo.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
  sudo: a password is required
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/test
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/test/test-rosping.test
  open: No such file or directory
  elf_open: Invalid argument
  WARNING: exit code 1 from a shell command.
  ERROR: Execution of '/jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/temp/run.do_install.48620' failed with exit code 1:
  [1/2] cd /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/build && sudo -n sh -c 'cd /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/devel/lib/rosping; chown root.root rosping; chmod 4755 rosping' || ( echo ^[[34m#\ type\ following\ command\ before\ execute\ rosping...\ sudo\ chown\ root.root\ ./bin/rosping\;\ sudo\ chmod\ 4755\ ./bin/rosping^[[0m )
  ERROR: ld.so: object 'libpseudo.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
  sudo: a password is required
  # type following command before execute rosping... sudo chown root.root ./bin/rosping; sudo chmod 4755 ./bin/rosping
  [1/2] cd /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/build && /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/recipe-sysroot-native/usr/bin/cmake -P cmake_install.cmake
  -- Install configuration: ""
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/lib/pkgconfig/rosping.pc
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/cmake/rospingConfig.cmake
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/cmake/rospingConfig-version.cmake
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/package.xml
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/lib/rosping/rosping
  ERROR: ld.so: object 'libpseudo.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
  sudo: a password is required
  -- Installing: /jenkins/mjansa/build/ros/ros1-melodic-gatesgarth/tmp-glibc/work/core2-64-oe-linux/rosping/2.1.13-1-r0/image/opt/ros/melodic/share/rosping/test

Signed-off-by: Martin Jansa <martin.jansa@lge.com>