{foxy} resolve dependency issues from last foxy update
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-pyproj' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geodesy_1.0.4-1.bb DEPENDS on or otherwise requires it). Close matches:
  python3-pyproj
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-catkin-pkg' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geodesy_1.0.4-1.bb DEPENDS on or otherwise requires it). Close matches:
  python-catkin-pkg
  python3-catkin-pkg
ERROR: Nothing PROVIDES 'UNRESOLVED-python3-argcomplete' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/nodl/ros2nodl_0.1.0-1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-libxmlrpc-c++' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ifm3d-core/ifm3d-core_0.18.0-4.bb DEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'rqt-common-plugins' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/variants/desktop_0.9.1-1.bb RDEPENDS on or otherwise requires it)
rqt-common-plugins was skipped: Recipe is blacklisted: qt5: rdepends on rqt-image-view which depends on qt-gui-cpp, rqt-gui, rqt-gui-cpp which depend on qtbase; pyqt5: rdepends on rqt-image-view which depends on qt-gui-cpp, rqt-gui, rqt-gui-cpp which depend on python3-pyqt5 which requires pyqt5
NOTE: Runtime target 'rqt-common-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rqt-common-plugins']
ERROR: Nothing RPROVIDES 'desktop' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/variants/desktop_0.9.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'desktop'
NOTE: Runtime target 'desktop' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desktop']
ERROR: Nothing RPROVIDES 'desktop-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/variants/desktop_0.9.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'desktop-dev'
NOTE: Runtime target 'desktop-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desktop-dev']
ERROR: Nothing RPROVIDES 'rviz-default-plugins' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/variants/desktop_0.9.1-1.bb RDEPENDS on or otherwise requires it)
rviz-default-plugins was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz-default-plugins']
ERROR: Nothing RPROVIDES 'rviz2' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/variants/desktop_0.9.1-1.bb RDEPENDS on or otherwise requires it)
rviz2 was skipped: Recipe is blacklisted: qt5: depends on qtbase; opengl: depends on rviz-ogre-vendor which depends on mesa which is not available because of missing opengl or vulkan in DISTRO_FEATURES; x11: depends on rviz-rendering which depends on rviz-ogre-vendor which depends on libx11,libxrandr,libxaw which require x11 in DISTRO_FEATURES
NOTE: Runtime target 'rviz2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rviz2']
ERROR: Nothing RPROVIDES 'geodesy-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geodesy_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'geodesy-dev'
NOTE: Runtime target 'geodesy-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geodesy-dev']
ERROR: Nothing RPROVIDES 'geodesy' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geodesy_1.0.4-1.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geographic-info_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'geodesy'
NOTE: Runtime target 'geodesy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geodesy']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-pyproj' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geodesy_1.0.4-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-pyproj' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-pyproj']
ERROR: Nothing RPROVIDES 'packagegroup-ros-world-foxy' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros-common/recipes-core/packagegroups/packagegroup-ros-world.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-ros-world-foxy'
NOTE: Runtime target 'packagegroup-ros-world-foxy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-foxy']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-foxy']
ERROR: Nothing RPROVIDES 'ifm3d-core' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ifm3d-core/ifm3d-core_0.18.0-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ifm3d-core'
NOTE: Runtime target 'ifm3d-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ifm3d-core']
ERROR: Nothing RPROVIDES 'geographic-info' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geographic-info_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'geographic-info'
NOTE: Runtime target 'geographic-info' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geographic-info']
ERROR: Nothing RPROVIDES 'ros2nodl' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/recipes-core/packagegroups/packagegroup-ros-world-foxy.bb, /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/nodl/ros2nodl_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros2nodl'
NOTE: Runtime target 'ros2nodl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2nodl']
ERROR: Nothing RPROVIDES 'geographic-info-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/geographic-info/geographic-info_1.0.4-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'geographic-info-dev'
NOTE: Runtime target 'geographic-info-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['geographic-info-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-argcomplete' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/nodl/ros2nodl_0.1.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-argcomplete' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-argcomplete']
ERROR: Nothing RPROVIDES 'ros2nodl-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/nodl/ros2nodl_0.1.0-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ros2nodl-dev'
NOTE: Runtime target 'ros2nodl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2nodl-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libxmlrpc-c++' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ifm3d-core/ifm3d-core_0.18.0-4.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libxmlrpc-c++' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libxmlrpc-c++']
ERROR: Nothing RPROVIDES 'ifm3d-core-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/ifm3d-core/ifm3d-core_0.18.0-4.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'ifm3d-core-dev'
NOTE: Runtime target 'ifm3d-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ifm3d-core-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-libusb-1.0' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/phidgets-drivers/libphidget22_2.0.2-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-libusb-1.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-outputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-drivers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-drivers', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-drivers-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-drivers-dev', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-ik' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-ik', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-ik-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-ik-dev', 'phidgets-digital-outputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-outputs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-outputs-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-gyroscope-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-gyroscope-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-gyroscope' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-gyroscope', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-motors-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-motors-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-motors' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-motors', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-inputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-inputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-digital-inputs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-digital-inputs-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-spatial-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-spatial-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-spatial' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-spatial', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-high-speed-encoder' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-high-speed-encoder', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-high-speed-encoder-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-high-speed-encoder-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-temperature' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-temperature', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-temperature-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-temperature-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-magnetometer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-magnetometer', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-magnetometer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-magnetometer-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-analog-inputs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-analog-inputs', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-analog-inputs-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-analog-inputs-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-accelerometer' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-accelerometer', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-accelerometer-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-accelerometer-dev', 'phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-api' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-api', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'phidgets-api-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['phidgets-api-dev', 'libphidget22', 'UNRESOLVED-libusb-1.0']
NOTE: Runtime target 'libphidget22' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidget22', 'UNRESOLVED-libusb-1.0']
ERROR: Nothing RPROVIDES 'libphidget22-dev' (but /jenkins/mjansa/build/ros/ros2-foxy-dunfell/meta-ros/meta-ros2-foxy/generated-recipes/phidgets-drivers/libphidget22_2.0.2-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'libphidget22-dev'
NOTE: Runtime target 'libphidget22-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidget22-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>