{foxy} rviz-ogre-vendor: depend on platform ogre and prevent the use of ExternalProject_Add
* otherwise it fails to build, because it cannot find string.h include
  from RSS
ERROR: rviz-ogre-vendor-8.0.2-1-r0 do_compile: Execution of 'ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/temp/run.do_compile.4295' failed with exit code 1:
[1/3] cd ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1-build && ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/cmake --build . && ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build
FAILED: ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build
cd ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1-build && ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/cmake --build . && ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/cmake -E touch ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build
[1/524] ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DOGRE_GCC_VISIBILITY -DOGRE_MESHLODGENERATOR_EXPORTS -Iros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/Components/MeshLodGenerator/include -Iros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include -Iinclude -Wall -Winit-self -Wcast-qual -Wwrite-strings -Wextra -Wundef -Wmissing-declarations -Wno-unused-parameter -Wshadow -Wno-missing-field-initializers -Wno-long-long  -std=c++14 -w -Wno-everything -msse -O2 -g -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++11 -MD -MT Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o -MF Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o.d -o Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o -c Components/MeshLodGenerator/OgreMeshLodGenerator_pch_dephelp.cxx
FAILED: Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o
ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/x86_64-oe-linux-g++  -DOGRE_GCC_VISIBILITY -DOGRE_MESHLODGENERATOR_EXPORTS -Iros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/Components/MeshLodGenerator/include -Iros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include -Iinclude -Wall -Winit-self -Wcast-qual -Wwrite-strings -Wextra -Wundef -Wmissing-declarations -Wno-unused-parameter -Wshadow -Wno-missing-field-initializers -Wno-long-long  -std=c++14 -w -Wno-everything -msse -O2 -g -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++11 -MD -MT Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o -MF Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o.d -o Components/MeshLodGenerator/CMakeFiles/OgreMeshLodGenerator_pch_dephelp.dir/OgreMeshLodGenerator_pch_dephelp.cxx.o -c Components/MeshLodGenerator/OgreMeshLodGenerator_pch_dephelp.cxx
In file included from ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include/OgreRoot.h:32,
                 from ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/Components/MeshLodGenerator/src/OgreMeshLodPrecompiledHeaders.h:32,
                 from Components/MeshLodGenerator/OgreMeshLodGenerator_pch_dephelp.cxx:1:
ros2-foxy-dunfell/tmp-glibc/work/core2-64-oe-linux/rviz-ogre-vendor/8.0.2-1-r0/build/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include/OgrePrerequisites.h:37:10: fatal error: string: No such file or directory
   37 | #include <string>

Signed-off-by: Martin Jansa <martin.jansa@lge.com>